version: "3.8"
services:
  frontend:
    image: phonebook-frontend
    build:
      context: ./frontend
      dockerfile: ./frontend/Dockerfile
    container_name: phonebook-frontend

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: phonebook-reverse-proxy
    depends_on:
      - frontend

  backend:
    image: phonebook-backend
    build:
      context: ./backend
      dockerfile: ./backend/Dockerfile
    container_name: phonebook-backend
    environment:
      - MONGODB_URI=mongodb+srv://fullstack:UIXQ6YpwFNMGGdy6@cluster0.gbuly.mongodb.net/FullstackPhonebookApp?retryWrites=true&w=majority
