name: Scheduled health check

on:
  schedule:
    - cron: "42 4 * * 0,3"
  push:
    branches:
      - master

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v2
        with:
          url: https://quiet-oasis-04315.herokuapp.com/health
          max-attempts: 3
          retry-delay: 5s
